### ISSUE TITLE
Please bump base and hlint

### ISSUE THREAD

**Issue by ezzieyguywuf** [reflex-frp/patch#25]
I have successfully compiled and executed the test suite using the following:

- `ghc-8.10.3`
- `base-4.14.1.0`
- `hlint-3.2.3`

If you are able  to do this and push a new release, this will allow us to better support this package in gentoo.

**Comment by ali-abrar** [comment]
Fixed as of [0.0.3.2 revision 2](http://hackage.haskell.org/package/patch-0.0.3.2/revisions/).
